name: CI

on: [push]

env:
  DEFAULT_PYTHON: 3.9

jobs:
  lint-black:
    name: Check black
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from github
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v2
        id: python
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Install pre-commit
        run : |
            pre-commit install
      - name: Run black
        run: |
          pre-commit run --hook-stage manual black --all-files --show-diff-on-failure

  lint-flake8:
    name: Check flake8
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from github
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v2
        id: python
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements_dev.txt
      - name: Install pre-commit
        run : |
            pre-commit install
      - name: Run flake8
        run: |
          pre-commit run --hook-stage manual flake8 --all-files

  lint-isort:
    name: Check isort
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from github
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v2
        id: python
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements_dev.txt
      - name: Run flake8
        run: |
          isort setup.py srpenergy tests

  lint-other:
    name: Check other linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from github
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v2
        id: python
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements_dev.txt
      - name: Install pre-commit
        run : |
            pre-commit install
      - name: Run check-yaml
        run: |
          pre-commit run --hook-stage commit check-yaml --all-files --show-diff-on-failure
      - name: Run codespell
        run: |
          pre-commit run --hook-stage commit codespell --all-files --show-diff-on-failure
      - name: Run bandit
        run: |
          pre-commit run --hook-stage commit bandit --all-files --show-diff-on-failure
      - name: Run end-of-file-fixer
        run: |
          pre-commit run --hook-stage commit end-of-file-fixer --all-files --show-diff-on-failure
      - name: Run trailing-whitespace
        run: |
          pre-commit run --hook-stage commit trailing-whitespace --all-files --show-diff-on-failure
      - name: Run rstcheck
        run: |
          pre-commit run --hook-stage commit rstcheck --all-files --show-diff-on-failure

  pylint:
    name: Check pylint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from github
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v2
        id: python
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Analysing the code with pylint
        run: |
          pylint setup.py srpenergy tests

  pytest:
    runs-on: ubuntu-latest
    needs:
      - lint-black
      - lint-other
      - lint-isort
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Check out code from github
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Run tests
        run: |
          python --version
          python -m pytest --cov=srpenergy --cov-report=xml  \
            -o console_output_style=count \
            -p no:sugar \
            tests
