name: Publish tag to Test Pypi

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Publish to Repo'
        required: true
        default: 'testpypi'
        type: choice
        options:
        - pypi
        - testpypi

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish package to TestPyPI
      if: ${{ github.event.inputs.target_environment == 'testpypi' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN  }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish package to PyPI
      if: ${{ github.event.inputs.target_environment == 'pypi' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN  }}
