name: Publish PyPI

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag name'
        required: true
        default: '1.3.7'
      target_environment:
        description: 'Publish to Repo'
        required: true
        default: 'testpypi'
        type: choice
        options:
        - pypi
        - testpypi
env:
  PYTHON_VERSION: "3.10"

jobs:

  build:
    name: Build distribution
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}

    steps:
    - uses: actions/checkout@v4.1.2
      with:
        ref:  '${{ github.event.inputs.release_tag }}'

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade build twine
        pip install build

    - name: Build package
      run: python -m build

    - name: Check package
      run: twine check dist/*

    - name: Upload artifact
      id: artifact-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          dist/*.tar.gz
          dist/*.whl
        retention-days: 2

    - name: Output artifact ID
      run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    steps:

    - uses: actions/checkout@v4.1.2
      with:
        ref:  '${{ github.event.inputs.release_tag }}'

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Publish package to TestPyPI
      if: ${{ github.event.inputs.target_environment == 'testpypi' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN  }}
        repository-url: https://test.pypi.org/legacy/

    - name: Publish package to PyPI
      if: ${{ github.event.inputs.target_environment == 'pypi' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN  }}
